baseURL: "dustinzielke.com" 
title: Dustin Zielke
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

      # menu:
      # main:
      #- name: Books
      #    url: books/
      #    weight: 1 
      #  - name: Papers
      #   url: papers/
      #   weight: 2
      # - name: Courses
      #   url: courses/
      #   weight: 3
      # - name: Data
      #   url: data/
      #   weight: 4 
      # - name: Blog
      #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
      #   weight: 5

params:
    description: "I am an academic researcher, writer, and instructor working in phenomenological philosophy. Currently, I focus on the phenomenology of selfhood, meaning, time, and the event."
    author: Dustin Zielke
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Dustin Zielke
          subtitle: "I am an academic researcher, writer, and instructor working in phenomenological philosophy. Currently, I focus on the phenomenology of selfhood, meaning, time, and the event."
          imageUrl: "headshot_red.JPG"
          imageWidth: 240
          imageHeight: 240
          imageTitle: Dustin Zielke
          buttons:
            # - name: Books
            #  url: books/
            # - name: Papers
            #   url: papers/
            # - name: Courses
            #   url: courses/
            # - name: Data
            # url: data/
            # - name: Tags
            #  url: tags/
            # - name: Archive
            #  url: archive/
            # - name: Blog
            #  url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: Email
          url: mailto:omicron_batting.0x@icloud.com
        - name: academia
          url: https://camosun.academia.edu/DustinZielke
            # - name: CV
            # url: cv.pdf
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=qtFA794AAAAJ&hl=en&citsig=AM0yFClT_-MOmJ7LPik8brLGkUot&ref=thoughtsinways.com
            # - name: Location
            # url: location/
            # - name: Office Hours
            # url: officehours/
            # - name: GitHub
            # url: https://github.com/pmichaillat
            # - name: YouTube
            # url: https://www.youtube.com/@alexandermccallsmithoffici9000
            # - name: Twitter
            # url: https://twitter.com/McCallSmith

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Dustin Zielke"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
